// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.12
// source: internal/proto/gommand.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	WorkDir string `protobuf:"bytes,2,opt,name=workDir,proto3" json:"workDir,omitempty"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_gommand_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gommand_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_internal_proto_gommand_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Command) GetWorkDir() string {
	if x != nil {
		return x.WorkDir
	}
	return ""
}

type CommandResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stdout  string `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	StdErr  string `protobuf:"bytes,2,opt,name=stdErr,proto3" json:"stdErr,omitempty"`
	Command string `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_gommand_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gommand_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_internal_proto_gommand_proto_rawDescGZIP(), []int{1}
}

func (x *CommandResult) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *CommandResult) GetStdErr() string {
	if x != nil {
		return x.StdErr
	}
	return ""
}

func (x *CommandResult) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type Managment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommandName string   `protobuf:"bytes,1,opt,name=commandName,proto3" json:"commandName,omitempty"`
	Args        []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *Managment) Reset() {
	*x = Managment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_gommand_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Managment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Managment) ProtoMessage() {}

func (x *Managment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gommand_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Managment.ProtoReflect.Descriptor instead.
func (*Managment) Descriptor() ([]byte, []int) {
	return file_internal_proto_gommand_proto_rawDescGZIP(), []int{2}
}

func (x *Managment) GetCommandName() string {
	if x != nil {
		return x.CommandName
	}
	return ""
}

func (x *Managment) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type CommandListResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*CommandTmp `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *CommandListResult) Reset() {
	*x = CommandListResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_gommand_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandListResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandListResult) ProtoMessage() {}

func (x *CommandListResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gommand_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandListResult.ProtoReflect.Descriptor instead.
func (*CommandListResult) Descriptor() ([]byte, []int) {
	return file_internal_proto_gommand_proto_rawDescGZIP(), []int{3}
}

func (x *CommandListResult) GetItems() []*CommandTmp {
	if x != nil {
		return x.Items
	}
	return nil
}

type CommandTmp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ExecTmp     string   `protobuf:"bytes,2,opt,name=execTmp,proto3" json:"execTmp,omitempty"`
	DefaultArgs []string `protobuf:"bytes,3,rep,name=defaultArgs,proto3" json:"defaultArgs,omitempty"`
	WrapperName string   `protobuf:"bytes,4,opt,name=wrapperName,proto3" json:"wrapperName,omitempty"`
	Timeout     string   `protobuf:"bytes,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Sync        bool     `protobuf:"varint,6,opt,name=sync,proto3" json:"sync,omitempty"`
	ActionName  string   `protobuf:"bytes,7,opt,name=actionName,proto3" json:"actionName,omitempty"`
	Shell       string   `protobuf:"bytes,8,opt,name=shell,proto3" json:"shell,omitempty"`
	WorkDir     string   `protobuf:"bytes,9,opt,name=workDir,proto3" json:"workDir,omitempty"`
}

func (x *CommandTmp) Reset() {
	*x = CommandTmp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_gommand_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandTmp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandTmp) ProtoMessage() {}

func (x *CommandTmp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gommand_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandTmp.ProtoReflect.Descriptor instead.
func (*CommandTmp) Descriptor() ([]byte, []int) {
	return file_internal_proto_gommand_proto_rawDescGZIP(), []int{4}
}

func (x *CommandTmp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CommandTmp) GetExecTmp() string {
	if x != nil {
		return x.ExecTmp
	}
	return ""
}

func (x *CommandTmp) GetDefaultArgs() []string {
	if x != nil {
		return x.DefaultArgs
	}
	return nil
}

func (x *CommandTmp) GetWrapperName() string {
	if x != nil {
		return x.WrapperName
	}
	return ""
}

func (x *CommandTmp) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

func (x *CommandTmp) GetSync() bool {
	if x != nil {
		return x.Sync
	}
	return false
}

func (x *CommandTmp) GetActionName() string {
	if x != nil {
		return x.ActionName
	}
	return ""
}

func (x *CommandTmp) GetShell() string {
	if x != nil {
		return x.Shell
	}
	return ""
}

func (x *CommandTmp) GetWorkDir() string {
	if x != nil {
		return x.WorkDir
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_gommand_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_gommand_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_proto_gommand_proto_rawDescGZIP(), []int{5}
}

var File_internal_proto_gommand_proto protoreflect.FileDescriptor

var file_internal_proto_gommand_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x67, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3d, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x6f,
	0x72, 0x6b, 0x44, 0x69, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x77, 0x6f, 0x72,
	0x6b, 0x44, 0x69, 0x72, 0x22, 0x59, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x64, 0x45, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x74, 0x64, 0x45, 0x72, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22,
	0x41, 0x0a, 0x09, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72,
	0x67, 0x73, 0x22, 0x3c, 0x0a, 0x11, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x27, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x6d, 0x70, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x22, 0xfc, 0x01, 0x0a, 0x0a, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x6d, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x78, 0x65, 0x63, 0x54, 0x6d, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x78, 0x65, 0x63, 0x54, 0x6d, 0x70, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x41, 0x72, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x41, 0x72, 0x67, 0x73, 0x12,
	0x20, 0x0a, 0x0b, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x79, 0x6e, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x73, 0x79, 0x6e, 0x63, 0x12,
	0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x68, 0x65, 0x6c, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x73, 0x68, 0x65, 0x6c, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x6f, 0x72, 0x6b, 0x44, 0x69, 0x72,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x77, 0x6f, 0x72, 0x6b, 0x44, 0x69, 0x72, 0x22,
	0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0x79, 0x0a, 0x07, 0x47, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x12, 0x35, 0x0a, 0x0b, 0x45, 0x78, 0x65, 0x63, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x12, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x0b, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x22, 0x00, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x67, 0x72, 0x34, 0x63, 0x32, 0x2d, 0x32, 0x30, 0x30, 0x30, 0x2f, 0x67, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_gommand_proto_rawDescOnce sync.Once
	file_internal_proto_gommand_proto_rawDescData = file_internal_proto_gommand_proto_rawDesc
)

func file_internal_proto_gommand_proto_rawDescGZIP() []byte {
	file_internal_proto_gommand_proto_rawDescOnce.Do(func() {
		file_internal_proto_gommand_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_gommand_proto_rawDescData)
	})
	return file_internal_proto_gommand_proto_rawDescData
}

var file_internal_proto_gommand_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_proto_gommand_proto_goTypes = []interface{}{
	(*Command)(nil),           // 0: proto.Command
	(*CommandResult)(nil),     // 1: proto.CommandResult
	(*Managment)(nil),         // 2: proto.Managment
	(*CommandListResult)(nil), // 3: proto.CommandListResult
	(*CommandTmp)(nil),        // 4: proto.CommandTmp
	(*Empty)(nil),             // 5: proto.Empty
}
var file_internal_proto_gommand_proto_depIdxs = []int32{
	4, // 0: proto.CommandListResult.items:type_name -> proto.CommandTmp
	0, // 1: proto.Gommand.ExecCommand:input_type -> proto.Command
	5, // 2: proto.Gommand.CommandList:input_type -> proto.Empty
	1, // 3: proto.Gommand.ExecCommand:output_type -> proto.CommandResult
	3, // 4: proto.Gommand.CommandList:output_type -> proto.CommandListResult
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_gommand_proto_init() }
func file_internal_proto_gommand_proto_init() {
	if File_internal_proto_gommand_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_gommand_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_gommand_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_gommand_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Managment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_gommand_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandListResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_gommand_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandTmp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_gommand_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_gommand_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_gommand_proto_goTypes,
		DependencyIndexes: file_internal_proto_gommand_proto_depIdxs,
		MessageInfos:      file_internal_proto_gommand_proto_msgTypes,
	}.Build()
	File_internal_proto_gommand_proto = out.File
	file_internal_proto_gommand_proto_rawDesc = nil
	file_internal_proto_gommand_proto_goTypes = nil
	file_internal_proto_gommand_proto_depIdxs = nil
}
