version: "3"
services:
  ubuntu:
    container_name: mokosza-test-runner
    build:
      context: ..
      dockerfile: .docker/env/Dockerfile
    volumes:
      - ../:/app
    networks:
      internal: